### PR TITLE
Lenient stackTraceLimit works across browsers

### LINKED ISSUE #525: Fix Error.stackTraceLimit assignment on Firefox
See https://github.com/Agoric/agoric-sdk/pull/2017

image

### PR DESCRIPTION
**Pull request by erights**
Fixes #525 

Using #590 to iterate within several browsers, I repaired several issues.

   * #525 was that assigning `Error.stackTraceLimit` was failing in non-v8-based browsers because `Error` had no such property and is frozen. Although the property is indeed non-standard and absent in non-v8 systems, Google's documentation encourages assignments to it anyway. This is a noop elsewhere, but is harmless when `Error` is unfrozen. To accommodate this practice, this PR installs a noop `Error.stackTraceLimit` accessor property on every platform. It is a noop everywhere except in the start compartment of a v8-based platform.
   * On the Safari browser (and presumably on any host using the JSC engine) `DataView` has a non-standard but non-deletable `BYTES_PER_ELEMENT` property whose value is a number. Since it is non-deletable but harmless, we added it to our whitelist.
   * We added logic for obtaining the stack string for FF (using the proposed `Error.prototype.stack` accessor property`) and others including Safari using the `error.stack` property if present. Otherwise (such as on XS currently) the default stack remains the empty string.

In the process, made the console output more pleasant for the common case of console messages containing only one error argument. For this case, nothing is gained by nesting the error within a group. Removing this extra visual noise helps this common case.

Because I built it using #590 it was easy to build it on #590 , which is fine if #590 gets merged first. If #590 gets delayed, I can make this independently mergeable since it has no logical dependence on #590.

### CODE REVIEW

**Review by dckc — COMMENTED** [review]
At a glance, I don't see anything wrong, but I'm not confident I could maintain this, so I'm inclined to leave it to others.

File: packages/ses/src/error/tame-error-constructor.js [hunk 1]
```diff
@@ -74,6 +87,55 @@ export default function tameErrorConstructor(
...
+        if (typeof OriginalError.stackTraceLimit === 'number') {
+          // OriginalError.stackTraceLimit is only on v8
+          return OriginalError.stackTraceLimit;
+        }
+        return undefined;
+      },
+      set(newLimit) {
+        if (typeof OriginalError.stackTraceLimit === 'number') {
+          // OriginalError.stackTraceLimit is only on v8
+          OriginalError.stackTraceLimit = newLimit;
```
Comment (warner) [inline packages/ses/src/error/tame-error-constructor.js:109]: If someone does `Error.stackTraceLimit = undefined` or `= 'oops'` or something surprising, would this preclude them from ever changing it back again? Node.js doesn't seem to complain when you assign a non-Number, at least not right away.

Fixing that might require a separate flag (recorded early, before anything has a change to modify `Error.stackTraceLimit`), which remembers whether we're on a platform that has it or not, rather than checking each time.

File: packages/ses/src/whitelist.js [hunk 2]
```diff
@@ -1101,6 +1101,7 @@ export const whitelist = {
   DataView: {
     // Properties of the DataView Constructor
     '[[Proto]]': '%FunctionPrototype%',
+    BYTES_PER_ELEMENT: 'number', // Non std but undeletable on Safari.
```
Comment (warner) [inline packages/ses/src/whitelist.js:1104]: Does this reveal something about the platform that could be a thread to determinism? Not that we can do much about it..

**Review by warner — APPROVED** [review]
Looks pretty good to me, but I'll defer to @michaelfig or @kriskowal as the real experts.

File: packages/ses/src/error/console.js [hunk 3]
```diff
@@ -224,32 +224,38 @@ const makeCausalConsole = (baseConsole, loggedErrorHandler) => {
...
 
   /**
-   * Logs the `subErrors` within a group named `label`.
+   * Logs the `subErrors` within a group name mentioning `optTag`.
    *
    * @param {string | undefined} optTag
    * @param {Error[]} subErrors
    * @returns {void}
    */
   const logSubErrors = (optTag = undefined, subErrors) => {
```
Comment (michaelfig) [inline packages/ses/src/error/console.js:233]: Not a blocker, but it's a little weird to have an optional argument before one that is mandatory.

**Review by michaelfig — APPROVED** [review]
LGTM.

File: packages/ses/src/error/tame-error-constructor.js (hunk 1 above)
Comment (erights) [reply packages/ses/src/error/tame-error-constructor.js:109]: Changed so that if `newLimit` is not a number, it is silently ignored. Added a comment explaining why.

File: packages/ses/src/whitelist.js (hunk 2 above)
Comment (erights) [reply packages/ses/src/whitelist.js:1104]: It falls within static implementation non-determinism https://github.com/tc39/proposal-ses#how-deterministic , just like sort order does. At some point when we have a fully deterministic specification, none of the browsers will implement it because of these sorts of static non-determinism. This static form of non-determinsm does not threaten security. It threatens only deterministic replication and replay, which we're never gonna try on browser JS engines anyway.

File: packages/ses/src/error/console.js (hunk 3 above)
Comment (erights) [reply packages/ses/src/error/console.js]: Fixed
