### PR TITLE
fix(ses)!: Simplify transforms

### LINKED ISSUE #321: Remove endowments from the compartment transforms API
Currently, the compartment transforms array carries an endowments object from each transform that needs to introduce endowments. Per #256, we’ve agreed that the APIs for introducing names to the global scope will include only the endowments to the `globalThis` specified as the first argument of the `Compartment` constructor, and non-enumerable global, lexically scoped, names introduced by calling `evaluate` with `const`, `let`, or `var`.

Per that consensus, this issue tracks specifically the work needed to remove endowments from the transform API.

### PR DESCRIPTION
**Pull request by kriskowal**
This change simplifies the compartment transforms for evaluated programs to just an array of functions that accept and return program strings.  The previous version of this API enabled transforms to add endowments and left room for future transformable properties.  We have elected to use the compartment `evaluate` function to introduce lexical endowments and `globalThis` to introduce enumerable and computable endowments.

Fixes #321

### CODE REVIEW

File: packages/ses/src/transforms.js [hunk 1]
```diff
@@ -95,6 +95,7 @@ export function rejectImportExpressions(src) {
 
 const someDirectEvalPattern = new RegExp('\\beval\\s*(?:\\(|/[/*])');
 
+// Exported for unit tests.
```
Comment (erights) [inline packages/ses/src/transforms.js:98]: Thanks for noting that.

For all these, what is needed so that the error here could carry more context that just the line number? (not suggesting any such change for this PR though.)

Comment (kriskowal) [reply packages/ses/src/transforms.js:98]: We could change the non-capture group for the body of the eval expression in the regular expression to a capture-group and report that. I imagine that could get quite unwieldy depending on the length of the expression.
