### PR TITLE
fix(ses): Distinguish intrinsics in start and non-start compartments

### LINKED ISSUE #317: Simplify intrinsic handling
The whole intrinsic management system now consists of nine separate files with too much redundancy, e.g., between `intrinsic-names.js`, `intrinsic-globals.js`, and `whitelist.js`. We should simplify, make it easier to maintain, and self-test consistency among what redundancy remains. Also, `check-intrinsics.js` seems vacuous. Bad edit from a previously meaningful state?

### LINKED ISSUE #385: SES: Improve realm record layering
As written today, performEval is a function that accepts a realmRec, and getCurrentRealmRec returns the only proper realmRec. Per a comment from @erights, we should curry the realmRec under performEval.

https://github.com/Agoric/SES-shim/pull/363#discussion_r453220239

### PR DESCRIPTION
**Pull request by erights**
Whitelists no longer painfully redundant.
Placeholder for multiple Compartment constructors, including one which only throws.

Start compartment has initial authority. Others do not. Independent of *Taming options. 
`{ *Taming: 'unsafe' }` is no longer about initial authority in start compartment, as long as it obeys ocap rules.
'unsafe' is now about enabling violations of ocap rules, such as primordials that are no longer powerless.
Lockdown *Taming options have much milder meaning.
   * We still check that they are only set to 'safe' or 'unsafe', with default 'safe'. 
   * `dateTaming` is ignored. Maybe we should just get rid of this flag. Transition problem?
   * `mathTaming` is ignored. Maybe we should just get rid of this flag. Transition problem?
   * `regExpTaming` is effectively ignored. But we may decide that 'unsafe' suppresses the deletion of `RegExp.prototype.compile`.
   * The new `localeTaming`, if set to 'unsafe', leaves the original `*Locale*` methods in place.

Finally we get to Error taming. Independent of the `errorTaming` option, the tamed powerful v8 API emulation remains on the start compartment's `Error` constructor. None of these are on the `Error` constructor of other compartments. However, this shows that we need a different knob: whether to expose engine-specific (e.g., v8 specific) APIs.

In a step towards https://tc39.es/proposal-error-stacks/ , we leave on the start compartment the powerful `getStackString(error)` function, which gives the stacktrace string associated with that error. Because this special power is only on the start compartment, we do not consider it a material violation of ocap rules, so it is there independent of `errorTaming`.

The violation of ocap rules which is pervasively available is the legacy behavior of `error.stack`, since it takes no privilege but violates information hiding. Accordingly, on v8 where we have control, under `errorTaming: 'safe'` (or default) this is truncated to the empty string. The 'unsafe' setting leaves the legacy behavior alone, providing the same string that the new `getStackString(error)` provides.

Fixes #317 
Fixes #385 by getting rid of the realmRec altogether.

### CODE REVIEW

**Comment by erights** [comment]
@kriskowal @warner I hit the "ready for review" button, though I am aware that this needs to be divided into smaller reviewable PRs. Nevertheless, it works, is a big improvement of the status quo, and even seems to work. Comments appreciated, especially on strategy for breaking it up.

**Comment by dckc** [comment]
@erights writes:
> In a step towards https://tc39.es/proposal-error-stacks/ , we leave on the start compartment the powerful `getStackString(error)` function, which gives the stacktrace string associated with that error. Because this special power is only on the start compartment, we do not consider it a material violation of ocap rules ...

yay! [unsealException](https://monte.readthedocs.io/en/latest/runtime.html#__entrypoint_io__.unsealException) restored to its former glory. (actually, I don't see it in erights.org nor https://github.com/kpreid/e-on-java ; did E have `unsealException`?)

**Comment by erights** [comment]
> yay! unsealException restored to its former glory. (actually, I don't see it in erights.org nor https://github.com/kpreid/e-on-java ; did E have unsealException?)

@kpreid Did you implement something that? (I remember us talking about it.)

**Comment by kpreid** [comment]
I implemented sealed exceptions in E-on-CL only.

Sealed exception primitives: https://github.com/kpreid/e-on-cl/blob/f93d188051c66db0ad4ff150bd73b838f7bc25ed/lisp/base.lisp#L75

The compiler implements sealing by transforming any exception (`condition` in CL terms) caught by a `CatchExpr` before passing it to the catch block code: https://github.com/kpreid/e-on-cl/blob/f93d188051c66db0ad4ff150bd73b838f7bc25ed/lisp/compiler-seq.lisp#L197

`unsealingConditionGuard(class)` makes guards which unseal exceptions and also match against the hidden type; this was intended to be the tool by which privileged E code accessed sealed exceptions: https://github.com/kpreid/e-on-cl/blob/f93d188051c66db0ad4ff150bd73b838f7bc25ed/lisp/knot.lisp#L76

(The Lisp `e-condition-unseal` function is also used in the Updoc implementation and other diagnostic-type things)

File: packages/ses/src/lockdown-shim.js [hunk 1]
```diff
@@ -90,52 +92,69 @@ export function lockdown(options = {}) {
...
+    return true;
+  }
+  return hardenIntrinsics;
 }
+
+export const lockdown = (options = {}) => {
+  const optHardenIntrinsics = repairIntrinsics(options);
+  if (optHardenIntrinsics === false) {
+    return false;
+  }
```
Comment (kriskowal) [inline packages/ses/src/lockdown-shim.js:158]: This will probably be easier to force through type discipline if it’s “optional function” rather than “function or bool (and only ever specifically false)”.

This seems odd. I’ll try to find the rationale. Weird enough for a comment.

File: packages/ses/src/make-evaluate-factory.js [hunk 2]
```diff
@@ -1,5 +1,10 @@
 import { arrayJoin } from './commons.js';
 
+// The original unsafe untamed Function constructor, which must not escape.
+// Sample at module initialization time, which is before lockdown can
+// repair it. Use it only to build powerless abstractions.
+const FERAL_FUNCTION = Function;
```
Comment (kriskowal) [inline packages/ses/src/make-evaluate-factory.js:6]: 👍 Clearly the opposite of tame. Implies existence of “dread function” and “dire function”.

File: packages/ses/test/identity-continuity.test.js [hunk 3]
```diff
@@ -33,8 +33,6 @@ test('identity Array', t => {
 
 // Compartment is a shared global
 test('identity Compartment', t => {
-  t.plan(7);
```
Comment (kriskowal) [inline packages/ses/test/identity-continuity.test.js:36]: Should bring this back.

**Comment by erights** [comment]
What is `%AllAllowListKeys%`? I don't think I have seen it before.

**Comment by erights** [comment]
Your extended comment of how to unpack this PR seems exactly right. Thanks!

**Comment by kriskowal** [comment]
I’ve decided to review this monolithically. That generally means more rounds of back-and-forth, but separating the mechanical changes from the semantic changes will in this case probably take longer than the review. So, I’m releasing the lock on this branch. I may instead push nit fix commits to the end in the process of a local holistic review, but will not force push.

File: packages/ses/src/lockdown-shim.js (hunk 1 above)
Comment (kriskowal) [reply packages/ses/src/lockdown-shim.js]: Posting a commit to this that keeps the two-stage lockdown without branching or type unions. `repairIntrinsics` returns a no-op (returns false) function called `alreadyHardenedIntrinsics` that serves both as an indicator and a callable function that satisfies the same type as `hardenIntrinsics`. `repairIntrinsics` returns a function named `maybeHardenIntrinsics` that is either `hardenIntrinsics` or `alreadyHardenedIntrinsics`.

File: packages/ses/src/intrinsics.js [hunk 4]
```diff
@@ -1,92 +1,142 @@
...
+  universalPropertyNames,
+  sharedGlobalPropertyNames,
+  whitelist,
+} from './whitelist.js';
 
-const { apply } = Reflect;
-const uncurryThis = fn => (thisArg, ...args) => apply(fn, thisArg, args);
-const hasOwnProperty = uncurryThis(Object.prototype.hasOwnProperty);
+// Like defineProperty, but throws if it would modify an existing property.
+export function initProperty(obj, name, desc) {
```
[the remark this answers is not in the document]
Comment (kriskowal) [reply packages/ses/src/intrinsics.js]: Addressed with a follow-up commit.

File: packages/ses/test/tame-date.test.js [hunk 5]
```diff
@@ -4,24 +4,47 @@ import '../src/main.js';
...
+function isDate(date) {
+  return (
+    Object.prototype.toString.call(date) === '[object Date]' &&
+    Number.isInteger(date.getTime())
+  );
+}
+
+test('lockdown start Date is powerful', t => {
+  t.assert(Number.isInteger(Date.now()));
+  t.ok(isDate(new Date()));
```
[the remark this answers is not in the document]
Comment (kriskowal) [reply packages/ses/test/tame-date.test.js]: Addressed with a follow-up commit.
