### PR TITLE
fix: restore locale methods safely

### LINKED ISSUE #335: tame x.toLocale functions?
I was reading through the docs for [String.prototype.toLocaleLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase), and noticed that its zero-argument behavior depends upon the host's default locale. In addition, the one- and array- argument behavior depends upon which locales are installed (the spec says it will choose the "best available" locale out of the list supplied).

I think there are other functions in the SES approved list that have similar behaviors. If I look at everything that mentions "Locale", I see:

* `Object.prototype.toLocale`
* `Number.prototype.toLocaleString`
* `BigInt.prototype.toLocaleString`
* `Date.prototype.toLocaleString`, `.toLocaleDateString`, and `.toLocaleTimeString`
* `String.prototype.localeCompare`, `.toLocaleLowerCase`, and `.toLocaleUpperCase`
* `Array.prototype.toLocaleString` (also for various TypedArrays)

I haven't tested this yet, but I see all those functions are approved, so I'm concerned that they'll expose nondeterminism to the SES environment.

Did we have an answer for this? I think we talked about defining SES as living in a world with a single fixed locale (maybe the `C` locale?), but I don't see anything obvious in the shim that might impose this.

### LINKED ISSUE #378: SES-0.9.0 vs rollup: uses toLocaleLowerCase, which was removed
I went to update agoric-sdk to use today's latest SES release (0.9.0), and ran into test failures. It looks like `rollup`, which we frequently run from inside a SES start compartment, uses `String.prototype.toLocaleLowerCase`. This was removed in 0.9.0. as part of #335 .

The relevant function in rollup is:

```js
function makeUnique(name, existingNames) {
    const existingNamesLowercase = new Set(Object.keys(existingNames).map(key => key.toLowerCase()));
    if (!existingNamesLowercase.has(name.toLocaleLowerCase()))
        return name;
    const ext = path.extname(name);
    name = name.substr(0, name.length - ext.length);
    let uniqueName, uniqueIndex = 1;
    while (existingNamesLowercase.has((uniqueName = name + ++uniqueIndex + ext).toLowerCase()))
        ;
    return uniqueName;
}
```

I'm guessing this would work well-enough if `toLocaleLowerCase` were to delegate to `toLowerCase`.

More generally, I'm more in favor of taming the `*Locale*` properties by retaining them, but pretending we live in a single pre-defined locale, like the `C` locale, which was one of the options we explored in #335 .

cc @erights

### PR DESCRIPTION
**Pull request by erights**
Rather than removing the `*Locale*` methods, replace them with their non-locale equivalents.

`String.prototype.localeCompare` doesn't seem to have a builtin non-locale equivalent, so we provide one.

Fixes #335 
Fixes #378 
See #379 
See https://github.com/Agoric/agoric-sdk/issues/1290

### CODE REVIEW

File: packages/ses/src/tame-locale-methods.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
+import { assert } from './assert.js';
+import { getOwnPropertyNames, defineProperty } from './commons.js';
+
+const localePattern = /\b(\w*[a-z])[L]ocale([A-Z]\w*\b)/;
```
Comment (kriskowal) [inline packages/ses/src/tame-locale-methods.js:4]: The initial and final break match might be better as expressly start and end of the whole string, `/^...$/` instead of `\b...\b`, though it would be hard for a vetted shim to tease out different behavior.

**Comment by erights** [comment]
Ready for review

File: packages/ses/src/tame-locale-methods.js [hunk 2]
```diff
@@ -0,0 +1,54 @@
+import { assert } from './assert.js';
+import { getOwnPropertyNames, defineProperty } from './commons.js';
+
+const localePattern = /^(\w*[a-z])[L]ocale([A-Z]\w*)$/;
```
Comment (kriskowal) [inline packages/ses/src/tame-locale-methods.js:4]: Is [L] intended to be alone in that group?

File: packages/ses/src/tame-locale-methods.js [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+// See https://tc39.es/ecma262/#sec-string.prototype.localecompare
+const nonLocaleCompare = function localeCompare(that) {
+  if (this === null || this === undefined) {
+    throw new TypeError(`this is not coercible`);
```
Comment (kriskowal) [inline packages/ses/src/tame-locale-methods.js:9]: Perhaps we can leave the debugger with a little more guidance, “Cannot localeCompare with null or undefined receiver”

File: packages/ses/src/tame-locale-methods.js [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+    const intrinsic = intrinsics[intrinsicName];
+    for (const methodName of getOwnPropertyNames(intrinsic)) {
+      const match = localePattern.exec(methodName);
+      if (match) {
+        assert(
+          typeof intrinsic[methodName] === 'function',
+          `expected ${methodName} to be a function`,
+        );
+        const nonLocaleMethodName = `${match[1]}${match[2]}`;
+        const method = intrinsic[nonLocaleMethodName];
```
Comment (kriskowal) [inline packages/ses/src/tame-locale-methods.js:45]: This might break in interesting ways if the language grows a new locale method that doesn’t have a corresponding non-locale-named method. Perhaps we should use an explicit list.

**Comment by kriskowal** [comment]
I left some nits. Also again, might be good to retroactively add an entry to the 0.9.0 notes about these methods being removed.

File: packages/ses/src/tame-locale-methods.js (hunk 2 above)
Comment (erights) [reply packages/ses/src/tame-locale-methods.js:4]: Good catch!

File: packages/ses/src/tame-locale-methods.js (hunk 4 above)
Comment (erights) [reply packages/ses/src/tame-locale-methods.js:45]: That's what the immediately following `assert` test on line 48 is about. Is it adequate?

Comment (kriskowal) [reply packages/ses/src/tame-locale-methods.js:47]: The assert ensures that we fail fast. Could we alternately just succeed since it would be culled?

**Comment by erights** [comment]
> Perhaps we can use this change to also add the missing release note for v0.9.0.

> Also again, might be good to retroactively add an entry to the 0.9.0 notes about these methods being removed.

Looks like @warner already added them -- the third bullet under 0.9.0. Is this what you had in mind?

**Comment by erights** [comment]
At https://github.com/Agoric/SES-shim/blob/master/packages/ses/NEWS.md which is on master

File: packages/ses/src/tame-locale-methods.js (hunk 4 above)
Comment (erights) [reply packages/ses/src/tame-locale-methods.js:47]: culled?

**Comment by kriskowal** [comment]
> At https://github.com/Agoric/SES-shim/blob/master/packages/ses/NEWS.md which is on master

Sneaky. https://github.com/Agoric/SES-shim/commit/579fb12064607e5d9f7c3e3ae10f0d37ba582c70

Thank you @warner!

File: packages/ses/src/tame-locale-methods.js (hunk 4 above)
Comment (kriskowal) [reply packages/ses/src/tame-locale-methods.js:47]: If my intuition is right, any method not expressly in the list of allowed methods would be deleted by lockdown, after taming. So, if a shim or future version of the language added a method with Locale in its name and no corresponding non-locale method, we don’t need to tame it. There’s also some chance that any new non-locale method isn’t a suitable replacement.

Comment (erights) [reply packages/ses/src/tame-locale-methods.js:47]: That all makes sense. But does it suggest any change to this PR before I merge?

File: packages/ses/src/whitelist.js [hunk 5]
```diff
@@ -737,7 +737,7 @@ export default {
     indexOf: fn,
     // 21.1.3.9 String.prototype.lastIndexOf
     lastIndexOf: fn,
-    // 21.1.3.10 String.prototype.localeCompare suppressed
+    // 21.1.3.10 String.prototype.localeCompare
     localeCompare: false,
```
Comment (erights) [inline packages/ses/src/whitelist.js:741]: BUG BUG BUG. This should have been changed from `false` to `fn`. With it as `false`, `localeCompare` was still being removed. Amusing but sad why the tests passed anyway. Fixing both now.

File: packages/ses/src/tame-locale-methods.js [hunk 6]
```diff
@@ -0,0 +1,56 @@
+import { assert } from './assert.js';
+import { getOwnPropertyNames, defineProperty } from './commons.js';
+
+const localePattern = /^(\w*[a-z])Locale([A-Z]\w*)$/;
+
+// See https://tc39.es/ecma262/#sec-string.prototype.localecompare
+const nonLocaleCompare = function localeCompare(that) {
```
Comment (erights) [inline packages/ses/src/tame-locale-methods.js:7]: Fixing the omission of `localCompare` revealed yet another bug. Here, I define a replacement function with `function`. This does not adequately emulate a builtin method. `function` functions have constructor behavior and `.prototype` property. Builtin methods do not. Instead, we need to use concise method syntax.

File: packages/ses/src/tame-locale-methods.js (hunk 4 above)
Comment (erights) [reply packages/ses/src/tame-locale-methods.js:53]: IIUC, the culling question does not suggest any change to the PR so I'll proceed to merge. Please let me know if I'm missing something.
